name: Build & Push Docker Image

on:
  push:
    branches:
      - play

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (for Maven cache only, not needed for Docker)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image (multi-stage)
        run: |
          docker build --build-arg COMMIT_HASH=${GITHUB_SHA} -t tanverit16/spring-security:${GITHUB_SHA} .
          docker push tanverit16/spring-security:${GITHUB_SHA}

  deploy:
    name: Deploy to self-hosted runners
    runs-on: ${{ matrix.runner }}
    needs: build
    strategy:
      matrix:
        runner: [dsi-1, dsi-2, dsi-3]

    steps:
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: |
          docker pull tanverit16/spring-security:${GITHUB_SHA}

      - name: Stop and Remove Existing Container
        run: |
          docker stop spring-app || true
          docker rm spring-app || true

      - name: Run Docker Container with VM_HOSTNAME Argument
        run: |
          docker run -d \
            --name spring-app \
            -p 8080:8080 \
            -e VM_HOSTNAME=$(hostname) \
            tanverit16/spring-security:${GITHUB_SHA}
