name: Build & Push Docker Image

on:
  push:
    branches:
      - play

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker Image
        run: |
          docker build --build-arg COMMIT_HASH=${GITHUB_SHA} -t tanverit16/spring-security:${GITHUB_SHA} .
          docker tag tanverit16/spring-security:${GITHUB_SHA} tanverit16/spring-security:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push tanverit16/spring-security:${GITHUB_SHA}
          docker push tanverit16/spring-security:latest

  deploy:
    name: Deploy to 192.168.0.130
    runs-on: self-hosted  # Runner must be set up on 192.168.0.130
    needs: build

    steps:
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: |
          docker pull tanverit16/spring-security:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop spring-app || true
          docker rm spring-app || true

      - name: Run Docker Container with VM_HOSTNAME Argument
        run: |
          docker run -d \
            --name spring-app \
            -p 8080:8080 \
            tanverit16/spring-security:latest \
            --vm.hostname=$(hostname)
